name: CMake on Multiple Platforms

on:
  push:
    branches: ["tests", "maim"]
  pull_request:
    branches: ["tests"]

env:
  BUILD_TYPE: Debug
  APP_DIR: candle-app 

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            compiler: gcc
            version: "11.2.0"
          - os: ubuntu-latest
            compiler: gcc
            version: "13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.version }}

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw --version=${{ matrix.version }} -y

      - name: Configure CMake
        working-directory: ${{ env.APP_DIR }}
        run: cmake -B build

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: cmake --build build

      - name: Test
        working-directory: ${{ env.APP_DIR }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}